name: Integration

on: [push, pull_request]

jobs:
  API_TESTING:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
 
    - run: npm run api-tests